import React,{useState}from"react";
import{Activity,AlertCircle,Bell,BookOpen,Bot,CheckCircle2,ChevronDown,Clock3,FileText,Grid2X2,Home,KeyRound,Laptop,LockKeyhole,Menu,Paperclip,Search,Send,Settings,ShieldCheck,Ticket,UserCircle2,Users,X,MonitorDown}from"lucide-react";

const base=[
{id:"REQ-1042",title:"Software Installation - Visual Studio Code",type:"Software Installation",status:"Approved",date:"Today, 02:15 PM",icon:MonitorDown},
{id:"REQ-1041",title:"Password Reset",type:"Password Reset",status:"Resolved",date:"Yesterday, 11:32 AM",icon:KeyRound},
{id:"REQ-1038",title:"Application Access - Jira",type:"Application Access",status:"In Progress",date:"30 Jun 2025, 05:20 PM",icon:Grid2X2},
{id:"REQ-1035",title:"Software Installation - Chrome",type:"Software Installation",status:"Resolved",date:"28 Jun 2025, 03:45 PM",icon:MonitorDown},
{id:"REQ-1031",title:"Password Change",type:"Password Change",status:"Resolved",date:"27 Jun 2025, 01:10 PM",icon:LockKeyhole}];

function App(){
 const[active,setActive]=useState("Dashboard"),[msg,setMsg]=useState(""),[search,setSearch]=useState(""),[requests,setRequests]=useState(base),[chat,setChat]=useState([{r:"bot",t:"Hello Sai Tharun! 👋 I'm your AutoDeskAI assistant. You can ask me about password reset, software installation, or application access."}]),[modal,setModal]=useState(null),[mobile,setMobile]=useState(false);
 const nav=[["Dashboard",Home],["AI Assistant",Bot],["My Requests",Ticket],["Request Software",Laptop],["Application Access",Grid2X2],["Knowledge Base",BookOpen],["Admin Panel",Users],["Audit Logs",Activity],["Settings",Settings]];
 const send=(text=msg)=>{text=text.trim();if(!text)return;setChat(c=>[...c,{r:"user",t:text}]);setMsg("");setTimeout(()=>{let t="I've understood your request. I'll validate the required information and permissions before proceeding.",title="IT Support Request",type="General Support";if(/install|software|chrome|visual studio|vscode/i.test(text)){t="I've identified this as a Software Installation request. I'll check whether the software is approved and whether you have the required permissions.";title="Software Installation - Request";type="Software Installation"}else if(/password|reset|change/i.test(text)){t="I've identified this as a Password request. I'll route it through the password workflow.";title="Password Reset";type="Password Reset"}else if(/access|jira|application/i.test(text)){t="I've identified this as an Application Access request. I'll check your permissions before submitting it.";title="Application Access Request";type="Application Access"}setChat(c=>[...c,{r:"bot",t}]);setRequests(r=>[{id:"REQ-"+(1043+r.length),title,type,status:"In Progress",date:"Just now",icon:Ticket},...r])},450)};
 const filtered=requests.filter(x=>(x.title+x.type+x.status).toLowerCase().includes(search.toLowerCase()));
 return <div className="app">
  <aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><div className="brandIcon"><Bot size={24}/></div><div><b>AutoDeskAI</b><small>AI Powered IT Helpdesk</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div>
   <nav>{nav.map(([n,I])=><button className={active===n?"nav active":"nav"} onClick={()=>{setActive(n);setMobile(false)}}><I size={18}/><span>{n}</span>{n==="Admin Panel"&&<ChevronDown size={14}/>}</button>)}</nav>
   <div className="sideFoot"><b>Smarter IT Support.</b><span>Faster Solutions.</span></div>
  </aside><div className={mobile?"overlay show":"overlay"} onClick={()=>setMobile(false)}/>
  <main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search for anything... (e.g. reset password, install software)"/></div><div className="headRight"><button className="bell"><Bell size={19}/><i>2</i></button><div className="user"><div className="avatar">ST</div><div><b>Sai Tharun V</b><small>Employee</small></div><ChevronDown size={15}/></div></div></header>
   <section className="content"><div className="intro"><div><h1>Good Afternoon, Sai Tharun 👋</h1><p>Welcome to AutoDeskAI — Your AI powered IT Helpdesk. How can we help you today?</p></div><div className="date">Tuesday, 1 July 2025<br/><b>02:24 PM</b></div></div>
    <div className="stats">{[["Total Requests",requests.length+7,Ticket],["Resolved",10,CheckCircle2],["In Progress",requests.filter(x=>x.status==="In Progress").length,Clock3],["Pending",0,AlertCircle]].map(([n,v,I],i)=><div className="stat"><div className={"statIcon s"+i}><I size={19}/></div><span>{n}</span><b>{v}</b><small className={i<2?"green":"red"}>{i<2?"↑":"↓"} {i===0?"20%":i===1?"25%":i===2?"50%":"100%"} <em>vs last 7 days</em></small></div>)}</div>
    <div className="grid"><section className="card assistant"><div className="cardHead"><div className="title"><div className="bot"><Bot size={21}/></div><div><b>AI Assistant</b><small>Describe your IT request in natural language. I'll handle it for you.</small></div></div><span className="online">● Online</span></div>
      <div className="chat">{chat.map((m,i)=><div className={m.r==="user"?"row user":"row"}>{m.r==="bot"&&<div className="mini bot"><Bot size={15}/></div>}<div className="bubble">{m.t}{i===0&&m.r==="bot"&&<ul><li>Password reset or change</li><li>Software installation</li><li>Application access</li></ul>}</div>{m.r==="user"&&<div className="mini person"><UserCircle2 size={20}/></div>}</div>)}</div>
      <div className="composer"><button><Paperclip/></button><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Type your message here..."/><button className="send" onClick={()=>send()}><Send size={17}/></button></div>
    </section>
    <aside className="right"><section className="card quick"><h2>Quick Actions</h2><div className="quickGrid">{[["Reset Password","Change or reset your password",KeyRound,"I need to reset my password."],["Install Software","Request approved software",MonitorDown,"I need to install Visual Studio Code."],["Access Application","Get access to applications",Grid2X2,"I need access to Jira."],["View All Requests","Check your request history",FileText,null]].map(([n,d,I,p])=><button onClick={()=>p?send(p):setActive("My Requests")}><div className="qicon"><I size={17}/></div><div><b>{n}</b><small>{d}</small></div></button>)}</div></section>
     <section className="card recent"><div className="sectionHead"><h2>Recent Requests</h2><button onClick={()=>setActive("My Requests")}>View All</button></div>{filtered.slice(0,5).map(r=>{let I=r.icon||Ticket;return <button className="request" onClick={()=>setModal(r)}><div className="reqIcon"><I size={15}/></div><div><b>{r.title}</b><span className={"status "+r.status.toLowerCase().replace(" ","-")}>{r.status}</span></div><time>{r.date}</time></button>})}</section>
    </aside></div>
    <div className="infoRow"><div><ShieldCheck/><b>Secure by design</b><span>Authorization is checked before controlled IT actions.</span></div><div><FileText/><b>Audit ready</b><span>Requests and execution results can be tracked centrally.</span></div><div><Bot/><b>AI assisted</b><span>Natural-language requests map to supported workflows.</span></div></div>
   </section></main>
   {modal&&<div className="modalBg" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(null)}><X/></button><div className="modalIcon"><Ticket/></div><small>{modal.id}</small><h2>{modal.title}</h2><p>Request type: <b>{modal.type}</b></p><span className={"status "+modal.status.toLowerCase().replace(" ","-")}>{modal.status}</span><div className="note"><ShieldCheck size={17}/> Backend authorization will be checked before execution.</div></div></div>}
 </div>
}
export default App;