"""Central configuration; never print credential values."""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent / '.env', override=False)
DATABASE_URL = os.getenv('DATABASE_URL', 'postgresql+psycopg://localhost/autodeskaidb')
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', '')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_EXPIRE_MINUTES = int(os.getenv('JWT_EXPIRE_MINUTES', '60'))
OLLAMA_HOST = os.getenv('OLLAMA_HOST', 'http://localhost:11434')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'qwen3:8b')
OLLAMA_TIMEOUT = int(os.getenv('OLLAMA_TIMEOUT', '90'))
TASK_TIMEOUT_SECONDS = int(os.getenv('TASK_TIMEOUT_SECONDS', '600'))
DEVICE_OFFLINE_SECONDS = int(os.getenv('DEVICE_OFFLINE_SECONDS', '120'))
ENTRA_TENANT_ID = os.getenv('ENTRA_TENANT_ID', '')
ENTRA_CLIENT_ID = os.getenv('ENTRA_CLIENT_ID', '')
ENTRA_GRAPH_CLIENT_ID = os.getenv('ENTRA_GRAPH_CLIENT_ID', '')
ENTRA_GRAPH_CLIENT_SECRET = os.getenv('ENTRA_GRAPH_CLIENT_SECRET', '')
ENTRA_TEST_ACCOUNT_UPN = os.getenv('ENTRA_TEST_ACCOUNT_UPN', '').strip().lower()
ENTRA_SSPR_URL = os.getenv('ENTRA_SSPR_URL', 'https://passwordreset.microsoftonline.com/')
JIRA_BASE_URL = os.getenv('JIRA_BASE_URL', '').rstrip('/')
JIRA_EMAIL = os.getenv('JIRA_EMAIL', '')
JIRA_API_TOKEN = os.getenv('JIRA_API_TOKEN', '')
JIRA_PROJECT_KEY = os.getenv('JIRA_PROJECT_KEY', '')
JIRA_TEST_ACCOUNT_EMAIL = os.getenv('JIRA_TEST_ACCOUNT_EMAIL', '').strip().lower()
JIRA_TEST_ACCOUNT_ID = os.getenv('JIRA_TEST_ACCOUNT_ID', '')
