import React,{useEffect,useRef,useState}from'react';
import{Activity,AlertCircle,Bell,BookOpen,Bot,CheckCircle2,ChevronDown,Clock3,FileText,Grid2X2,Home,KeyRound,Laptop,LockKeyhole,LogOut,Menu,MonitorDown,Search,Send,Settings,ShieldCheck,Ticket,UserCircle2,Users,X}from'lucide-react';

const label=x=>(x||'PENDING').replaceAll('_',' ');
const title=x=>({SOFTWARE_INSTALL:'Software Installation',ACCESS_REQUEST:'Application Access',PASSWORD_RESET:'Password Reset',PASSWORD_CHANGE:'Password Change',CLARIFICATION:'More Information Needed'}[x.intent]||'IT Support Request');
const icon=x=>x.intent==='SOFTWARE_INSTALL'?MonitorDown:x.intent==='ACCESS_REQUEST'?Grid2X2:x.intent?.startsWith('PASSWORD_')?KeyRound:Ticket;
const initials=x=>(x||'User').split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase();

export default function App(){
 const[token,setToken]=useState(''),[user,setUser]=useState(null),[mode,setMode]=useState('login'),[active,setActive]=useState('Dashboard'),[mobile,setMobile]=useState(false);
 const[requests,setRequests]=useState([]),[devices,setDevices]=useState([]),[chat,setChat]=useState([]),[msg,setMsg]=useState(''),[search,setSearch]=useState(''),[selectedDevice,setSelectedDevice]=useState(''),[clarify,setClarify]=useState(null),[retryKey,setRetryKey]=useState(null);
 const[busy,setBusy]=useState(false),[error,setError]=useState(''),[modal,setModal]=useState(null),[admin,setAdmin]=useState({users:[],requests:[],devices:[],audit:[]}),[catalog,setCatalog]=useState({software:[],applications:[]}),[enrollment,setEnrollment]=useState(null);
 const session=useRef('');
 async function api(path,options={}){let response;try{response=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}})}catch{throw new Error('Backend unavailable. Start FastAPI and retry.')}let data;try{data=await response.json()}catch{throw new Error('The backend returned an invalid response.')}if(!response.ok){if(response.status===401&&token&&session.current===token)logout();const d=data.detail;throw new Error(response.status===401?'Your session expired. Please sign in again.':typeof d==='string'?d:Array.isArray(d)?d.map(x=>x.msg).join('. '):'Request failed.')}return data}
 async function act(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function logout(){session.current='';setToken('');setUser(null);setRequests([]);setDevices([]);setChat([]);setActive('Dashboard')}
 async function refresh(){const[r,d]=await Promise.all([api('/requests'),api('/devices')]);if(session.current===token){setRequests(r);setDevices(d)}}
 async function refreshAdmin(){const[u,r,d,a,c]=await Promise.all([api('/admin/users'),api('/admin/requests'),api('/admin/devices'),api('/admin/audit'),api('/catalog')]);if(session.current===token){setAdmin({users:u,requests:r,devices:d,audit:a});setCatalog(c)}}
 useEffect(()=>{if(!token)return;let live=true;const poll=async()=>{try{if(live){await refresh();if(user?.role==='admin'&&['Admin Panel','Audit Logs'].includes(active))await refreshAdmin()}}catch(e){if(live)setError(e.message)}};poll();const timer=setInterval(poll,5000);return()=>{live=false;clearInterval(timer)}},[token,active]);
 useEffect(()=>{if(user&&!chat.length)setChat([{r:'bot',t:`Hello ${user.name}! I can help with password reset or change, approved software installation, and application access.`}])},[user]);
 async function authenticate(e){e.preventDefault();const f=new FormData(e.currentTarget),password=f.get('password');await act(async()=>{if(mode==='register')await api('/auth/register',{method:'POST',body:JSON.stringify({name:f.get('name'),email:f.get('email'),password})});const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password})});session.current=r.access_token;setToken(r.access_token);setUser(r.user)})}
 async function send(text=msg){text=text.trim();if(!text||busy)return;setChat(c=>[...c,{r:'user',t:text}]);setMsg('');await act(async()=>{const key=retryKey||crypto.randomUUID();setRetryKey(key);const r=await api('/requests',{method:'POST',body:JSON.stringify({message:text,device_id:selectedDevice?Number(selectedDevice):null,previous_request_id:clarify,idempotency_key:key})});setRetryKey(null);setClarify(r.status==='NEEDS_CLARIFICATION'?r.id:null);setChat(c=>[...c,{r:'bot',t:r.message,id:r.id,status:r.status}]);await refresh()})}
 if(!user)return <Auth mode={mode} setMode={setMode} submit={authenticate} busy={busy} error={error}/>;
 const filtered=requests.filter(x=>(title(x)+x.status+x.message).toLowerCase().includes(search.toLowerCase()));
 const nav=[['Dashboard',Home],['AI Assistant',Bot],['My Requests',Ticket],['Request Software',Laptop],['Application Access',Grid2X2],['Knowledge Base',BookOpen],...(user.role==='admin'?[['Admin Panel',Users],['Audit Logs',Activity]]:[]),['Settings',Settings]];
 const resolved=requests.filter(x=>x.status==='COMPLETED').length,progress=requests.filter(x=>['PENDING','PROCESSING'].includes(x.status)).length,needs=requests.filter(x=>x.status==='NEEDS_CLARIFICATION').length;
 return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><Brand close={()=>setMobile(false)}/><nav>{nav.map(([n,I])=><button key={n} className={active===n?'nav active':'nav'} onClick={()=>{setActive(n);setMobile(false)}}><I size={18}/><span>{n}</span>{n==='Admin Panel'&&<ChevronDown size={14}/>}</button>)}</nav><div className="sideFoot"><b>Smarter IT Support.</b><span>Controlled, policy-based actions.</span></div></aside><div className={mobile?'overlay show':'overlay'} onClick={()=>setMobile(false)}/><main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your requests..."/></div><div className="headRight"><button className="bell"><Bell size={19}/>{needs>0&&<i>{needs}</i>}</button><div className="user"><div className="avatar">{initials(user.name)}</div><div><b>{user.name}</b><small>{user.role}</small></div></div><button className="logout" onClick={logout}><LogOut size={18}/></button></div></header><section className="content">{error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}<div className="simulation"><ShieldCheck size={16}/>Prototype simulation: no real passwords, OS software, or external application access are changed.</div>
 {active==='Dashboard'&&<><div className="intro"><div><h1>Welcome, {user.name}</h1><p>Your authenticated, AI-assisted IT service desk.</p></div><div className="date">{new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}<br/><b>{new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</b></div></div><div className="stats">{[['Total Requests',requests.length,Ticket],['Resolved',resolved,CheckCircle2],['In Progress',progress,Clock3],['Needs Input',needs,AlertCircle]].map(([n,v,I],i)=><div className="stat" key={n}><div className={'statIcon s'+i}><I size={19}/></div><span>{n}</span><b>{v}</b><small>Live backend data</small></div>)}</div><div className="grid"><Chat chat={chat} msg={msg} setMsg={setMsg} send={send} busy={busy} devices={devices} selected={selectedDevice} setSelected={setSelectedDevice} clarify={clarify} cancel={()=>setClarify(null)}/><aside className="right"><Quick send={send} all={()=>setActive('My Requests')}/><Recent rows={filtered.slice(0,5)} open={setModal} all={()=>setActive('My Requests')}/></aside></div><Info/></>}
 {active==='AI Assistant'&&<Chat full chat={chat} msg={msg} setMsg={setMsg} send={send} busy={busy} devices={devices} selected={selectedDevice} setSelected={setSelectedDevice} clarify={clarify} cancel={()=>setClarify(null)}/>}
 {active==='My Requests'&&<Requests rows={filtered} open={setModal} confirm={id=>act(async()=>{await api(`/requests/${id}/password/confirm`,{method:'POST',body:JSON.stringify({confirm_simulation:true})});await refresh()})} reply={id=>{setClarify(id);setActive('AI Assistant')}}/>}
 {active==='Request Software'&&<Workflow title="Request approved software" description="Choose your registered device. The endpoint agent must be online." devices={devices} selected={selectedDevice} setSelected={setSelectedDevice} action={()=>send('Install VS Code')} button="Install VS Code"/>}
 {active==='Application Access'&&<Workflow title="Application access" description="Access is decided by backend policy, never by the AI." action={()=>send('I need access to Tableau')} button="Request Tableau access"/>}
 {active==='Knowledge Base'&&<Knowledge/>}{active==='Settings'&&<Profile user={user} devices={devices}/>}
 {active==='Admin Panel'&&<Admin data={admin} catalog={catalog} enrollment={enrollment} setEnrollment={setEnrollment} act={act} api={api} refresh={refreshAdmin}/>} {active==='Audit Logs'&&<Audit rows={admin.audit}/>}</section></main>{modal&&<RequestModal row={modal} close={()=>setModal(null)} api={api}/>}</div>
}

function Brand({close}){return <div className="brand"><div className="brandIcon"><Bot size={24}/></div><div><b>AutoDeskAI</b><small>AI Powered IT Helpdesk</small></div>{close&&<button className="close" onClick={close}><X/></button>}</div>}
function Auth({mode,setMode,submit,busy,error}){return <div className="authPage"><section className="authHero"><Brand/><h1>IT support that understands your request.</h1><p>Securely request password help, approved software, or application access from one workspace.</p><div className="heroPoints"><span><ShieldCheck/>Backend-controlled authorization</span><span><Activity/>Complete audit history</span><span><Bot/>Private local AI classification</span></div></section><section className="authCard"><div><h2>{mode==='login'?'Welcome back':'Create employee account'}</h2><p>{mode==='login'?'Sign in to open your service desk.':'Register, then sign in automatically.'}</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit}>{mode==='register'&&<label>Full name<input name="name" required maxLength="100"/></label>}<label>Email address<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required minLength={mode==='register'?12:1} maxLength="256" autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode==='register'&&<small>Use at least 12 characters.</small>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button className="authSwitch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New employee? Create an account':'Already registered? Sign in'}</button></div></section></div>}
function Chat({chat,msg,setMsg,send,busy,devices,selected,setSelected,clarify,cancel,full}){return <section className={'card assistant '+(full?'full':'')}><div className="cardHead"><div className="title"><div className="bot"><Bot size={21}/></div><div><b>AI Assistant</b><small>Describe one supported request. Never enter credentials.</small></div></div><span className="online">● Online</span></div><div className="deviceBar"><label>Installation device <select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a registered device</option>{devices.filter(x=>x.status==='ACTIVE').map(x=><option value={x.id} key={x.id}>{x.hostname} · {x.os_info}</option>)}</select></label>{!devices.length&&<small>An administrator must enroll your device before installation.</small>}</div><div className="chat">{chat.map((m,i)=><div className={m.r==='user'?'row user':'row'} key={i}>{m.r==='bot'&&<div className="mini bot"><Bot size={15}/></div>}<div className="bubble">{m.t}{m.id&&<small>Request #{m.id} · {label(m.status)}</small>}</div>{m.r==='user'&&<div className="mini person"><UserCircle2 size={20}/></div>}</div>)}</div>{clarify&&<div className="clarify">Replying to request #{clarify}<button onClick={cancel}>Cancel</button></div>}<form className="composer" onSubmit={e=>{e.preventDefault();send()}}><input value={msg} onChange={e=>setMsg(e.target.value)} maxLength="1000" placeholder="Type your IT request..."/><button className="send" disabled={busy||!msg.trim()}><Send size={17}/></button></form></section>}
function Quick({send,all}){return <section className="card quick"><h2>Quick Actions</h2><div className="quickGrid">{[['Reset Password','Controlled password workflow',KeyRound,'I forgot my password'],['Install Software','Request approved software',MonitorDown,'Install VS Code'],['Access Application','Backend policy decision',Grid2X2,'I need access to Tableau'],['View All Requests','Check request history',FileText,null]].map(([n,d,I,p])=><button key={n} onClick={()=>p?send(p):all()}><div className="qicon"><I size={17}/></div><div><b>{n}</b><small>{d}</small></div></button>)}</div></section>}
function Recent({rows,open,all}){return <section className="card recent"><div className="sectionHead"><h2>Recent Requests</h2><button onClick={all}>View All</button></div>{rows.length?rows.map(x=><RequestRow row={x} open={open} key={x.id}/>):<div className="empty">No requests yet.</div>}</section>}
function RequestRow({row,open}){const I=icon(row);return <button className="request" onClick={()=>open(row)}><div className="reqIcon"><I size={15}/></div><div><b>#{row.id} · {title(row)}</b><span className={'status '+row.status.toLowerCase()}>{label(row.status)}</span></div><time>{new Date(row.created_at+'Z').toLocaleDateString()}</time></button>}
function Requests({rows,open,confirm,reply}){return <section className="pageCard"><PageTitle title="My Requests" text="Statuses come directly from the backend and endpoint agent." icon={Ticket}/>{rows.length?rows.map(x=><article className="requestArticle" key={x.id}><RequestRow row={x} open={open}/><p>{x.message}</p>{x.status==='PENDING'&&x.intent.startsWith('PASSWORD_')&&<button onClick={()=>confirm(x.id)}>Confirm simulated operation</button>}{x.status==='NEEDS_CLARIFICATION'&&<button onClick={()=>reply(x.id)}>Provide information</button>}</article>):<div className="empty">No requests match your search.</div>}</section>}
function Workflow({title:heading,description,devices=[],selected,setSelected,action,button}){return <section className="pageCard workflow"><PageTitle title={heading} text={description} icon={ShieldCheck}/>{setSelected&&<label>Target device<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a device</option>{devices.map(x=><option value={x.id} key={x.id}>{x.hostname}</option>)}</select></label>}<button className="primary" onClick={action}>{button}</button></section>}
function Knowledge(){return <section className="pageCard"><PageTitle title="Knowledge Base" text="Supported workflows and their security boundaries." icon={BookOpen}/><div className="knowledge">{[[KeyRound,'Password help','The demo confirms a simulated identity operation and never sends passwords to Ollama.'],[MonitorDown,'Software installation','Only predefined software reaches your registered endpoint agent.'],[Grid2X2,'Application access','Backend policy makes the access decision. The AI cannot grant access.']].map(([I,h,p])=><article key={h}><I/><h3>{h}</h3><p>{p}</p></article>)}</div></section>}
function Profile({user,devices}){return <section className="pageCard"><PageTitle title="Profile & Settings" text="Your access token is held in memory; reloading signs you out." icon={Settings}/><div className="profile"><div className="bigAvatar">{initials(user.name)}</div><h2>{user.name}</h2><p>{user.email}</p><span className="role">{user.role}</span></div><h2>Registered devices</h2>{devices.length?devices.map(x=><Device row={x} key={x.id}/>):<div className="empty">No devices assigned.</div>}</section>}
function Device({row,action}){return <div className="device"><Laptop/><div><b>{row.hostname}</b><small>{row.device_id} · {row.os_info} · owner #{row.owner_user_id}</small></div>{action?<button onClick={action}>{row.status==='ACTIVE'?'Disable':'Enable'}</button>:<span className={'status '+row.status.toLowerCase()}>{row.status}</span>}</div>}
function Admin({data,catalog,enrollment,setEnrollment,act,api,refresh}){return <div className="adminGrid"><section className="pageCard"><PageTitle title="Admin Panel" text="Manage predefined capabilities and devices." icon={Users}/><h2>Approved software</h2>{catalog.software.map(x=><div className="policy" key={x.key}><span><b>{x.display_name}</b><small>{x.key}</small></span><button onClick={()=>act(async()=>{await api('/admin/software/'+x.key,{method:'PUT',body:JSON.stringify({enabled:!x.enabled,required_role:'employee'})});await refresh()})}>{x.enabled?'Disable':'Enable'}</button></div>)}<h2>Application policies</h2>{catalog.applications.map(x=><div className="policy" key={x.key}><span><b>{x.key}</b><small>{x.enabled?'Enabled':'Disabled'}</small></span><select value={x.required_role} onChange={e=>act(async()=>{await api('/admin/applications/'+x.key,{method:'PUT',body:JSON.stringify({enabled:x.enabled,required_role:e.target.value})});await refresh()})}><option value="employee">Employees and admins</option><option value="admin">Admins only</option></select><button onClick={()=>act(async()=>{await api('/admin/applications/'+x.key,{method:'PUT',body:JSON.stringify({enabled:!x.enabled,required_role:x.required_role})});await refresh()})}>{x.enabled?'Disable':'Enable'}</button></div>)}</section><section className="pageCard"><h2>Enroll endpoint device</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{setEnrollment(await api('/agent/register',{method:'POST',body:JSON.stringify({owner_user_id:Number(f.get('owner')),device_id:f.get('device_id'),hostname:f.get('hostname'),os_info:'Windows'})}));await refresh()})}}><label>Owner<select name="owner">{data.users.map(x=><option value={x.id} key={x.id}>{x.name} · {x.email}</option>)}</select></label><label>Device ID<input name="device_id" pattern="[a-zA-Z0-9_.-]+" required/></label><label>Hostname<input name="hostname" pattern="[a-zA-Z0-9_.-]+" required/></label><button className="primary">Enroll device</button></form>{enrollment&&<div className="tokenBox"><b>One-time agent token</b><p>Store this privately in the endpoint agent .env file.</p><input type="password" readOnly value={enrollment.agent_token} onFocus={e=>e.target.select()}/><button onClick={()=>setEnrollment(null)}>Dismiss</button></div>}<h2>Devices</h2>{data.devices.map(x=><Device row={x} key={x.id} action={()=>act(async()=>{await api('/admin/devices/'+x.id,{method:'PATCH',body:JSON.stringify({status:x.status==='ACTIVE'?'DISABLED':'ACTIVE'})});await refresh()})}/>)}</section><section className="pageCard wide"><h2>Users</h2><div className="simpleTable">{data.users.map(x=><div key={x.id}><span>#{x.id}</span><b>{x.name}</b><span>{x.email}</span><span className="role">{x.role}</span></div>)}</div></section></div>}
function Audit({rows}){return <section className="pageCard"><PageTitle title="Audit Logs" text="Backend-owned records contain no credentials." icon={Activity}/><div className="auditTable"><div className="auditHead"><b>Time</b><b>Action</b><b>User</b><b>Status</b></div>{rows.map(x=><div key={x.id}><span>{new Date(x.timestamp+'Z').toLocaleString()}</span><b>{x.action}</b><span>{x.user_id||'System'}</span><span className={'status '+x.status.toLowerCase()}>{x.status}</span></div>)}</div></section>}
function PageTitle({title:heading,text,icon:I}){return <div className="pageTitle"><div><h1>{heading}</h1><p>{text}</p></div><I/></div>}
function Info(){return <div className="infoRow">{[[ShieldCheck,'Secure by design','Authorization is checked before controlled actions.'],[FileText,'Audit ready','Requests and confirmed results are tracked.'],[Bot,'AI assisted','Local AI maps text to supported workflows.']].map(([I,b,s])=><div key={b}><I/><b>{b}</b><span>{s}</span></div>)}</div>}
function RequestModal({row,close,api}){const[history,setHistory]=useState([]),[failure,setFailure]=useState('');useEffect(()=>{api(`/requests/${row.id}/history`).then(setHistory).catch(e=>setFailure(e.message))},[row.id]);return <div className="modalBg" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={close}><X/></button><div className="modalIcon"><Ticket/></div><small>REQUEST #{row.id}</small><h2>{title(row)}</h2><p>{row.message}</p><span className={'status '+row.status.toLowerCase()}>{label(row.status)}</span><div className="note"><ShieldCheck size={17}/>Backend policy and authorization determine this result.</div><h3>History</h3>{failure&&<p className="error">{failure}</p>}{history.map(x=><div className="history" key={x.id}><b>{x.action}</b><small>{new Date(x.timestamp+'Z').toLocaleString()} · {x.status}</small></div>)}</div></div>}
